# Generated by Django 3.2.8 on 2021-12-28 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=40)),
                ('b_title', models.CharField(max_length=150)),
                ('b_author', models.CharField(max_length=40)),
                ('publish_date', models.DateField(default=datetime.date(2021, 12, 28))),
                ('total_quantity', models.BigIntegerField(max_length=5)),
                ('aval_quantity', models.BigIntegerField(max_length=5)),
            ],
        ),
    ]
