# Generated by Django 3.2.8 on 2021-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='aval_quantity',
            field=models.BigIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
